import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Caveat, Glass_Antiqua } from "next/font/google";
import { ModeToggle } from "@/components/theme-toggle-button";
import { Nav } from "@/components/shared/Nav";

const caveat = Caveat({ subsets: ["latin-ext"] });
const glass = Glass_Antiqua({ subsets: ["latin-ext"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={caveat.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Nav />
          {children}
          {/* footer */}
          <div className="mt-10 shadow-md shadow-foreground p-10 text-center">
            <p className="text-xl">© Artodo.cz {new Date().getFullYear()}</p>
            <span className="text-sm text-gray-500">web by Jirka Burdych</span>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
